AWSTemplateFormatVersion: '2010-09-09'

Parameters:

  Environment:
    Type: String
    Description: 'Identifier of the Environment'

  DBInstanceIdentifier:
    Type: String
    Description: 'Unique identifier for the MariaDB instance'
    MinLength: 1
    MaxLength: 63
    AllowedPattern: '^[a-zA-Z][a-zA-Z0-9-]*$'

  SnapshotIdentifier:
    Description: 'Identifier of the snapshot to restore from'
    Type: String

  SecurityGroupId:
    Description: The ID of an existing Security Group
    Type: 'AWS::EC2::SecurityGroup::Id'
    Default: sg-0191ec34cc21523d6

  VPCBkSimulator:
    Description: The ID of the existing Virtual Private Cloud (VPC)
    Type: 'String'
    Default: vpc-02ce562c4deeb740a
  
  AMISimulator:
    Type: String
    Description: 'Value AMI Simulator'
    Default: ami-079db87dc4c10ac91

  KeyNameSimulator:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: 'String'
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  
  S3BucketArtifact:
    Description: Name Of bucket S3 Save artifact
    Type: String

Resources:
  SSMAmiSimulator:
      Type: AWS::SSM::Parameter
      Properties:
        Name:
          Fn::Sub: /${Environment}/ami/simulator
        Tier: Standard
        Type: String
        Value:
          !Ref AMISimulator
  SSMArtifactBucket:
      Type: AWS::SSM::Parameter
      Properties:
        Name:
          Fn::Sub: /config/${Environment}/infra/bucket/artifacts
        Tier: Standard
        Type: String
        Value:
          !Ref S3BucketArtifact
  SSMVPCSimulator:
      Type: AWS::SSM::Parameter
      Properties:
        Name:
          Fn::Sub: /config/${Environment}/infra/vpc
        Tier: Standard
        Type: String
        Value:
          !Ref VPCBkSimulator
  SSMSecurityGroup:
      Type: AWS::SSM::Parameter
      Properties:
        Name:
          Fn::Sub: /config/${Environment}/infra/SG
        Tier: Standard
        Type: String
        Value:
          !Ref SecurityGroupId
  SecurityGroupBKsimulator:
    Type: 'AWS::EC2::SecurityGroup'
    DependsOn: ['SSMVPCSimulator', 'SSMSecurityGroup']
    Properties:
      GroupName: !Sub '${Environment}-bk-security-group'
      GroupDescription: New Security Group based on existing one
      VpcId: !GetAtt SSMVPCSimulator.Value
      SecurityGroupIngress:
        - IpProtocol: -1
          SourceSecurityGroupId: !GetAtt SSMSecurityGroup.Value
      SecurityGroupEgress:
        - IpProtocol: -1
          DestinationSecurityGroupId: !GetAtt SSMSecurityGroup.Value

  RDSStack:
    Type: 'AWS::CloudFormation::Stack'
    DependsOn: [SecurityGroupBKsimulator, SSMArtifactBucket, SSMVPCSimulator, SSMSecurityGroup]
    Properties:
      TemplateURL: !Sub 'https://{{resolve:ssm:/config/${Environment}/infra/bucket/artifacts}}.s3.${AWS::URLSuffix}.com/templates/RDSStack.yml'
      Parameters:
          ChildDBInstanceIdentifier: !Ref DBInstanceIdentifier
          ChildSnapshotIdentifier: !Ref SnapshotIdentifier
          ChildSecurityGroupId: !Ref SecurityGroupBKsimulator
  
  EC2Stack:
    Type: 'AWS::CloudFormation::Stack'
    DependsOn: [SecurityGroupBKsimulator, SSMAmiSimulator, SSMArtifactBucket, SSMVPCSimulator, SSMSecurityGroup]
    Properties:
      TemplateURL: 'https://{{resolve:ssm:/config/${Environment}/infra/bucket/artifacts}}.s3.${AWS::URLSuffix}.com/templates/EC2InstanceSimulatorStack.yml'
      Parameters:
        ChildKeyNameSimulator: !Ref KeyNameSimulator
        ChildSecurityGroupId: !Ref SecurityGroupBKsimulator
        ChildAmiSimulator: !GetAtt SSMAmiSimulator.Value